# jSecurity Configuration

# Default durations for temporary punishments.
# Format: 1d2h3m4s (d=days, h=hours, m=minutes, s=seconds)
default-durations:
  tempban: "12h"
  tempmute: "12h"

# Ban Evasion Prevention
# If true, players joining with the same IP as a banned player will also be banned.
prevent-ban-evasion: false

# New Player Announcements
# Announce when a new player joins the server.
announce-new-player: true
# Announce only when the total player count reaches one of these milestones.
# Leave empty to announce every new player.
# Example: [100, 200, 500, 1000]
announce-milestones: []