# jSecurity Configuration

# Default reasons for punishments if not specified.
default-reasons:
  ban: "You have been banned."
  mute: "You have been muted."

# Default durations for temporary punishments.
# Format: 1d2h3m4s (d=days, h=hours, m=minutes, s=seconds)
default-durations:
  tempban: "12h"
  tempmute: "12h"

# Ban Evasion Prevention
# If true, players joining with the same IP as a banned player will also be banned.
prevent-ban-evasion: false

# Broadcast and Kick Messages
# Placeholders: {player}, {staff}, {reason}, {duration}, {banned_player}
messages:
  ban-broadcast: "&c{player} has been permanently banned by {staff} for: {reason}"
  tempban-broadcast: "&c{player} has been temporarily banned by {staff} for {duration} for: {reason}"
  ipban-broadcast: "&c{player} has been IP banned by {staff}."
  mute-broadcast: "&c{player} has been permanently muted by {staff} for: {reason}"
  tempmute-broadcast: "&c{player} has been temporarily muted by {staff} for {duration} for: {reason}"
  unban-broadcast: "&a{player} has been unbanned by {staff}."
  unmute-broadcast: "&a{player} has been unmuted by {staff}."
  kick-broadcast: "&c{player} has been kicked by {staff} for: {reason}"

  kick-message: "&cYou have been kicked. Reason: {reason}"
  freeze-message: "&cYou have been frozen by a staff member."
  unfreeze-message: "&aYou have been unfrozen."

  ban-evasion-reason: "Ban Evasion ({banned_player})"

  kick-messages:
    ban: "&cYou have been permanently banned.\n&cReason: {reason}"
    tempban: "&cYou have been temporarily banned for {duration}.\n&cReason: {reason}"
    ipban: "&cYou have been IP banned."
    ban-evasion: "&cYour IP is associated with a banned account ({banned_player})."

  mute-message: "&cYou are currently muted. Reason: {reason}"
  tempmute-message: "&cYou are currently muted for {duration}. Reason: {reason}"