# JSecurity Configuration

# Default durations for temporary punishments.
# Format: 1d2h3m4s (d=days, h=hours, m=minutes, s=seconds)
default-durations:
  tempban: "12h"
  tempmute: "12h"

# Ban Evasion Prevention
# If true, players joining with the same IP as a banned player will also be banned.
prevent-ban-evasion: false

# New Player Announcements
# Announce when a new player joins the server.
announce-new-player: true
# Announce only when the total player count reaches one of these milestones.
# Leave empty to announce every new player.
# Example: [100, 200, 500, 1000]
announce-milestones: []

# Alt Account Detection
# If true, staff will be alerted when a player joins with the same IP as another player.
alt-account-alert: false

# Chat Delay
chat-delay:
  enabled: false
  # Delay in seconds
  period: 3

# Chat Filter
chat-filter:
  enabled: false
  blocked-keywords:
    - "www."
    - ".com"

# Keyword Replacement
keyword-replacement:
  enabled: false
  words:
    "fudge": ["fuck", "fck", "fk"]
    "poop": ["shit"]

# Muted Command Restriction
# A list of commands that are blocked for muted players.
# Commands should be listed without the initial slash (e.g., "msg" not "/msg").
muted-command-restriction:
  - "msg"
  - "tell"
  - "r"
  - "reply"
  - "me"

# Authentication System
# If true, players will be required to register and log in to play.
# This is intended for offline-mode (cracked) servers.
authentication:
  enabled: false
  min-password-length: 8
  max-password-length: 16
  password-must-contain:
    uppercase-letter: false
    number: false
    symbol: false
  join-at-spawn: true
  return-at-location: false
  join-on-blind: false
  join-on-spectator: false
  session-reconnection: false
  session-limit-timer: "6h"

# Database Configuration
database:
  type: "sqlite" # Can be "sqlite" or "mysql"
  host: "localhost"
  port: 3306
  name: "jsecurity"
  user: "username"
  password: "password"