name: JSecurity
version: 0.1.0
main: com.jerae.jsecurity.JSecurity
softdepend: [Purpur]
authors: [ Jerae ]
description: A security plugin for Minecraft servers.
commands:
  ban:
    description: Bans a player permanently.
    usage: /ban <player> [reason] [-s]
    permission: jsecurity.ban
  tempban:
    description: Temporarily bans a player.
    usage: /tempban <player> [duration] [reason] [-s]
    permission: jsecurity.tempban
  ipban:
    description: Bans a player's IP address.
    usage: /ipban <player/ip> [-s]
    permission: jsecurity.ipban
  unban:
    description: Unbans a player or IP address.
    usage: /unban <player/ip> [-s]
    permission: jsecurity.unban
  mute:
    description: Mutes a player permanently.
    usage: /mute <player> [reason] [-s]
    permission: jsecurity.mute
  tempmute:
    description: Temporarily mutes a player.
    usage: /tempmute <player> [duration] [reason] [-s]
    permission: jsecurity.tempmute
  unmute:
    description: Unmutes a player.
    usage: /unmute <player> [-s]
    permission: jsecurity.unmute
  kick:
    description: Kicks a player from the server.
    usage: /kick <player> [reason] [-s]
    permission: jsecurity.kick
  jsecurity:
    description: jSecurity admin commands.
    usage: /js <reload>
    permission: jsecurity.admin
    aliases: [js]
  message:
    description: Sends a private message to a player.
    usage: /message <player> <message>
    aliases: [msg]
  reply:
    description: Replies to the last private message.
    usage: /reply <message>
    aliases: [r]
  socialspy:
    description: Toggles social spy.
    usage: /socialspy
    permission: jsecurity.socialspy
  vanish:
    description: Toggles vanish mode.
    usage: /vanish
    permission: jsecurity.vanish
    aliases: [v]
  freeze:
    description: Freezes a player.
    usage: /freeze <player>
    permission: jsecurity.freeze
  unfreeze:
    description: Unfreezes a player.
    usage: /unfreeze <player>
    permission: jsecurity.unfreeze
  warn:
    description: Warns a player.
    usage: /warn <player> <reason> [-s]
    permission: jsecurity.warn
permissions:
  jsecurity.*:
    description: Gives access to all jSecurity commands.
    children:
      jsecurity.ban: true
      jsecurity.tempban: true
      jsecurity.ipban: true
      jsecurity.unban: true
      jsecurity.mute: true
      jsecurity.tempmute: true
      jsecurity.unmute: true
      jsecurity.kick: true
      jsecurity.admin: true
      jsecurity.freeze: true
      jsecurity.unfreeze: true
      jsecurity.warn: true
      jsecurity.alt.alert: true
      jsecurity.socialspy: true
      jsecurity.socialspy.view: true
      jsecurity.socialspy.exempt: true
      jsecurity.chat.delay.bypass: true
      jsecurity.vanish: true
      jsecurity.vanish.see: true
      jsecurity.vanish.interact: true
      jsecurity.vanish.silentjoin: true
      jsecurity.help: true
      jsecurity.record: true
      jsecurity.profile: true
      jsecurity.log: true
      jsecurity.history: true
      jsecurity.note: true
      jsecurity.message: true
      jsecurity.reply: true
      jsecurity.freeze: true
      jsecurity.unfreeze: true
  jsecurity.ban:
    description: Allows banning players.
  jsecurity.tempban:
    description: Allows temporarily banning players.
  jsecurity.ipban:
    description: Allows IP banning players.
  jsecurity.unban:
    description: Allows unbanning players.
  jsecurity.mute:
    description: Allows muting players.
  jsecurity.tempmute:
    description: Allows temporarily muting players.
  jsecurity.unmute:
    description: Allows unmuting players.
  jsecurity.kick:
    description: Allows kicking players.
  jsecurity.admin:
    description: Allows access to jSecurity admin commands.
  jsecurity.warn:
    description: Allows warning players.
  jsecurity.alt.alert:
    description: Notifies staff on possible alt account join.
  jsecurity.socialspy:
    description: Allows toggling social spy.
  jsecurity.socialspy.view:
    description: Allows viewing private messages with social spy.
  jsecurity.socialspy.exempt:
    description: Exempts a player from being spied on.
  jsecurity.chat.delay.bypass:
    description: Allows bypassing the chat delay.
  jsecurity.vanish:
    description: Allows toggling vanish mode.
  jsecurity.vanish.see:
    description: Allows seeing vanished players.
  jsecurity.vanish.interact:
    description: Allows interacting with players while vanished.
  jsecurity.vanish.silentjoin:
    description: Allows joining the server silently while vanished.
  jsecurity.help:
    description: Allows using the /js help command.
  jsecurity.record:
    description: Allows using the /js record command.
  jsecurity.profile:
    description: Allows using the /js profile command.
  jsecurity.log:
    description: Allows using the /js log command.
  jsecurity.history:
    description: Allows using the /js history command.
  jsecurity.note:
    description: Allows using the /js note command.
  jsecurity.message:
    description: Allows sending private messages.
  jsecurity.reply:
    description: Allows replying to private messages.
  jsecurity.freeze:
    description: Allows freezing players.
  jsecurity.unfreeze:
    description: Allows unfreezing players.