# jSecurity Configuration

# Default reasons for punishments if not specified.
default-reasons:
  ban: "You have been banned."
  mute: "You have been muted."

# Default durations for temporary punishments.
# Format: 1d2h3m4s (d=days, h=hours, m=minutes, s=seconds)
default-durations:
  tempban: "12h"
  tempmute: "12h"

# Ban Evasion Prevention
# If true, players joining with the same IP as a banned player will also be banned.
prevent-ban-evasion: false